name: DebugAssert Matrix

on:
  workflow_dispatch:
  push:

jobs:
  matrix:

    name: ${{ matrix.sys }} | SDK ${{ matrix.sdk }} | TestSDK ${{ matrix.testsdk }}

    strategy:
      fail-fast: false

      matrix:
        os:
          - windows-2022
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-15-intel
          - macos-latest

        arch:
          - x64
          - x86
          - arm64

        sdk:
          - "8.0.x"
          - "9.0.x"
          - "10.0.x"

        testsdk:
          - "17.11.1"
          - "18.7.0"

        exclude:
          - os: ubuntu-24.04
            arch: x86
          - os: ubuntu-24.04-arm
            arch: x64
          - os: ubuntu-24.04-arm
            arch: x86
          - os: macos-15-intel
            arch: x86
          - os: macos-15-intel
            arch: arm64
          - os: macos-latest
            arch: x64
          - os: macos-latest
            arch: x86
          - os: windows-2022
            arch: arm64

    runs-on: ${{ matrix.os }}

    env:

      SDK_VERSION: ${{ matrix.sdk }}
      TESTSDK_VERSION: ${{ matrix.testsdk }}

      TFM: ${{ matrix.sdk == '8.0.x' && 'net8.0'
            || matrix.sdk == '9.0.x' && 'net9.0'
            || matrix.sdk == '10.0.x' && 'net10.0' }}

    steps:

    - uses: actions/checkout@v4

    ####################################################################
    # Set paths
    ####################################################################

    - name: Set Paths (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $dir = "C:\w"

        New-Item -ItemType Directory -Force -Path $dir | Out-Null
        New-Item -ItemType Directory -Force -Path "$dir\temp" | Out-Null
        New-Item -ItemType Directory -Force -Path "$dir\dotnet" | Out-Null
        New-Item -ItemType Directory -Force -Path "$dir\work" | Out-Null

        Add-Content $env:GITHUB_ENV "WORKPATH=$dir\work"
        Add-Content $env:GITHUB_ENV "TMP=$dir\temp"
        Add-Content $env:GITHUB_ENV "TEMP=$dir\temp"
        Add-Content $env:GITHUB_ENV "TMPDIR=$dir\temp"
        Add-Content $env:GITHUB_ENV "DOTNET_INSTALL_DIR=$dir\dotnet"

    - name: Set Paths (Linux/macOS)
      if: runner.os != 'Windows'
      shell: pwsh
      run: |
        $dir = "${{ runner.temp }}/w"

        New-Item -ItemType Directory -Force -Path $dir | Out-Null
        New-Item -ItemType Directory -Force -Path "$dir/temp" | Out-Null
        New-Item -ItemType Directory -Force -Path "$dir/dotnet" | Out-Null
        New-Item -ItemType Directory -Force -Path "$dir/work" | Out-Null

        Add-Content $env:GITHUB_ENV "WORKPATH=$dir/work"
        Add-Content $env:GITHUB_ENV "TMP=$dir/temp"
        Add-Content $env:GITHUB_ENV "TEMP=$dir/temp"
        Add-Content $env:GITHUB_ENV "TMPDIR=$dir/temp"
        Add-Content $env:GITHUB_ENV "DOTNET_INSTALL_DIR=$dir/dotnet"

    ####################################################################
    # Display initial environment
    ####################################################################

    - name: Matrix Information
      shell: pwsh
      run: |
        Write-Host "=========================="
        Write-Host "Matrix"
        Write-Host "=========================="

        Write-Host "Runner OS       : $env:RUNNER_OS"
        Write-Host "Runner Arch     : $env:RUNNER_ARCH"
        Write-Host "Requested OS    : ${{ matrix.os }}"
        Write-Host "Requested Arch  : ${{ matrix.arch }}"

    - name: Verify environment
      shell: pwsh
      run: |
        Write-Host "DOTNET_INSTALL_DIR=$env:DOTNET_INSTALL_DIR"
        Write-Host "PROCESSOR_ARCHITECTURE=$env:PROCESSOR_ARCHITECTURE"

        if ($IsWindows) {
            cmd /c set
        } else {
            env | sort
        }

    ####################################################################
    # Install SDK
    ####################################################################

    - name: Setup .NET SDK
      if: matrix.arch != 'x86'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.SDK_VERSION }}

    - name: Setup .NET SDK (x86)
      if: matrix.arch == 'x86'
      uses: actions/setup-dotnet@v4
      env:
        PROCESSOR_ARCHITECTURE: x86
      with:
        dotnet-version: ${{ env.SDK_VERSION }}

    ####################################################################
    # Pin SDK
    ####################################################################

    - name: Generate global.json
      shell: pwsh
      run: |
        $sdk = dotnet --version

        @"
        {
          "sdk": {
            "version": "$sdk"
          }
        }
        "@ | Set-Content global.json

    ####################################################################
    # Dump SDK information
    ####################################################################

    - name: SDK Information
      shell: pwsh
      run: |
        Write-Host ""
        Write-Host "===== dotnet --version ====="
        dotnet --version

        Write-Host ""
        Write-Host "===== dotnet --info ====="
        dotnet --info

        Write-Host ""
        Write-Host "===== Installed SDKs ====="
        dotnet --list-sdks

        Write-Host ""
        Write-Host "===== Installed Runtimes ====="
        dotnet --list-runtimes

        Write-Host ""
        Write-Host "===== global.json ====="
        Get-Content global.json

    ####################################################################
    # Dump environment
    ####################################################################

    - name: Environment
      shell: pwsh
      run: |
        Get-ChildItem Env: |
          Sort-Object Name

    ####################################################################
    # Run experiment
    ####################################################################

    - name: Restore
      shell: pwsh
      run: |
        dotnet restore DebugAssertExperiment.slnx `
          -p:TargetFrameworks=${env:TFM} `
          -p:TestSdkVersion=${env:TESTSDK_VERSION}

    - name: Build
      shell: pwsh
      run: |
        dotnet build DebugAssertExperiment.slnx `
          -c Release `
          --no-restore `
          -p:TargetFrameworks=${env:TFM} `
          -p:TestSdkVersion=${env:TESTSDK_VERSION}

    - name: Test
      shell: pwsh
      run: |
        $args = @(
            "-c","Release",
            "--no-build",
            "--framework",$env:TFM,
            "--logger:console;verbosity=detailed",
            "--logger:trx",
            "--results-directory","TestResults",
            "-v:diag",
            "-p:TestSdkVersion=$env:TESTSDK_VERSION",
            "--", "RunConfiguration.TargetPlatform=${{ matrix.arch }}"
        )

        dotnet test DebugAssertExperiment.slnx @args

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: TestResults-${{ matrix.os }}-${{ matrix.arch }}-${{ env.TFM }}-${{ env.TESTSDK_VERSION }}
        path: TestResults